[["libbeam.so"]]
arch = "x86_64"
git-tree-sha1 = "c43f57f75e3616068cbe3c58e0e6471bd649f1e1"
libc = "glibc"
os = "linux"

    [["libbeam.so".download]]
    sha256 = "f2db93b91c14529767ce91ff2bb1c37f5e38b01e0af2f9c3633f2d6386008908"
    url = "https://github.com/torrance/MWAjl/raw/artifacts/x86_64/libbeam.so.tar.gz"

[["libcasacorejl.so"]]
arch = "x86_64"
git-tree-sha1 = "51ed75bb3fd0247b379e1c9debc548d8c37c917a"
libc = "glibc"
os = "linux"

    [["libcasacorejl.so".download]]
    sha256 = "0915eff9659ba505f22310552480de4ead78239c5ab983f08c08416b6035d0cf"
    url = "https://github.com/torrance/MWAjl/raw/artifacts/x86_64/libcasacorejl.so.tar.gz"
